# Tensor Tutorial

In [1]:
import torch
import numpy as np

Tensor Initialization

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
print(f"np_array: {np_array}")
x_np = torch.from_numpy(np_array)
print(f"x_up: {x_np}")

np_array: [[1 2]
 [3 4]]
x_up: tensor([[1, 2],
        [3, 4]])


In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data i.e., shape & datatype
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.2902, 0.6626],
        [0.6195, 0.4541]]) 



In [6]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)

print(f'Random Tensor: {rand_tensor}\n\n Ones Tensor: {ones_tensor}')

Random Tensor: tensor([[0.0160, 0.9937, 0.7780],
        [0.2995, 0.6019, 0.3050]])

 Ones Tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])


Tensor attributes - shape, datatype & device being stored on

In [7]:

tensor = torch.rand(3,4)

print(f"Tensor Shape: {tensor.shape}")
print(f"Tensor Datatype: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Tensor Shape: torch.Size([3, 4])
Tensor Datatype: torch.float32
Device tensor is stored on: cpu


Tensor Operations

In [8]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(f"Device is stored on: {tensor.device}")

Device is stored on: cpu


In [9]:
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor[:,1] = 0
tensor

tensor([[1, 0, 3],
        [4, 0, 6],
        [7, 0, 9]])

In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim = -2)
t1

tensor([[1, 0, 3],
        [4, 0, 6],
        [7, 0, 9],
        [1, 0, 3],
        [4, 0, 6],
        [7, 0, 9],
        [1, 0, 3],
        [4, 0, 6],
        [7, 0, 9]])

In [11]:
# element-wise product

print(f"tensor.mul(tensor): {tensor.mul(tensor)}\n\n")
print(f'tensor * tensor: {tensor * tensor}')

tensor.mul(tensor): tensor([[ 1,  0,  9],
        [16,  0, 36],
        [49,  0, 81]])


tensor * tensor: tensor([[ 1,  0,  9],
        [16,  0, 36],
        [49,  0, 81]])


In [12]:
# matrix multiplication

print(f"tensor.matmul(tensor): {tensor.matmul(tensor.T)}\n\n")
print(f"tensor @ tensor.T: {tensor @ tensor.T}")

tensor.matmul(tensor): tensor([[ 10,  22,  34],
        [ 22,  52,  82],
        [ 34,  82, 130]])


tensor @ tensor.T: tensor([[ 10,  22,  34],
        [ 22,  52,  82],
        [ 34,  82, 130]])


In [13]:
# operations with a _ are in-place; x_copy(y) & x.t_() will change x.

print(tensor, "\n\n")
tensor.add_(5)
print(tensor)

tensor([[1, 0, 3],
        [4, 0, 6],
        [7, 0, 9]]) 


tensor([[ 6,  5,  8],
        [ 9,  5, 11],
        [12,  5, 14]])


Numpy Bridge

In [14]:
# tensor to np array

t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [15]:
# change in the tensor will result in a change in the np array
t.add_(1)
print(f"t: {t}\n\nn: {n}")

t: tensor([2., 2., 2., 2., 2.])

n: [2. 2. 2. 2. 2.]


In [16]:
# np array to tensor
n = np.ones(5)

t = torch.from_numpy(n)

print(f"n: {n}\n\nt: {t}")

n: [1. 1. 1. 1. 1.]

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [17]:
np.add(n,5,out = n)

print(f"n: {n}\n\nt: {t}")

n: [6. 6. 6. 6. 6.]

t: tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
